name: Robot Tests

on:
  push:
    branches: [adding-robot-testing-automation]
  pull_request:
    branches: [adding-robot-testing-automation]
  workflow_dispatch: {}

jobs:
  run-robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/robot/requirements.txt

          - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-dependencies: true
          install-chromedriver: true

      - name: Start web app
        working-directory: client
        run: |
          npm ci
          nohup npm run dev &  # start frontend in background
          sleep 10             # wait until itâ€™s up

      - name: Run Robot tests
        working-directory: tests/robot
        run: |
          robot -d output tests/login-test.robot

      - name: Upload Robot reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-report
          path: tests/robot/output/
